---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: webhook-service
        namespace: system
        path: /mutate-lb-my-domain-v1-smartlb
    failurePolicy: Fail
    name: msmartlb.kb.io
    rules:
      - apiGroups:
          - lb.my.domain
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - smartlbs

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: webhook-service
        namespace: system
        path: /validate-lb-my-domain-v1-smartlb
    failurePolicy: Fail
    name: vsmartlb.kb.io
    rules:
      - apiGroups:
          - lb.my.domain
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - smartlbs
